### ISSUE TITLE
Error at grunt install

### ISSUE THREAD

**Issue by byRoadrunner** [Eluinhost/TeamspeakAuth#83]
Always when i want to run "grunt install" this Error comes:

root@MCRBTest:~/TeamspeakAuth# grunt install
Running "clean:bower" (clean) task

Running "bower-install-simple" task
Install Bower Dependencies
bower                            error Path must be a string. Received undefined

Stack trace:
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at Project._readInstalled (/root/TeamspeakAuth/node_modules/bower/lib/core/Project.js:589:26)
    at Project._analyse (/root/TeamspeakAuth/node_modules/bower/lib/core/Project.js:461:14)
    at Project.install (/root/TeamspeakAuth/node_modules/bower/lib/core/Project.js:48:17)
    at install (/root/TeamspeakAuth/node_modules/bower/lib/commands/install.js:27:20)
    at /root/TeamspeakAuth/node_modules/bower/lib/commands/index.js:21:32
    at Promise.apply (/root/TeamspeakAuth/node_modules/q/q.js:1078:26)
    at Promise.promise.promiseDispatch (/root/TeamspeakAuth/node_modules/q/q.js:741:41)
    at /root/TeamspeakAuth/node_modules/q/q.js:1304:14

Console trace:
Trace
    at StandardRenderer.error (/root/TeamspeakAuth/node_modules/bower/lib/renderers/StandardRenderer.js:82:17)
    at Logger.<anonymous> (/root/TeamspeakAuth/node_modules/grunt-bower-install-simple/tasks/grunt-bower-install-simple.js:81:22)
    at emitOne (events.js:96:13)
    at Logger.emit (events.js:188:7)
    at Logger.emit (/root/TeamspeakAuth/node_modules/bower-logger/lib/Logger.js:29:39)
    at /root/TeamspeakAuth/node_modules/bower/lib/commands/index.js:40:20
    at _rejected (/root/TeamspeakAuth/node_modules/q/q.js:797:24)
    at /root/TeamspeakAuth/node_modules/q/q.js:823:30
    at Promise.when (/root/TeamspeakAuth/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/root/TeamspeakAuth/node_modules/q/q.js:741:41)

System info:
Bower version: 1.3.12
Node version: 6.1.0
OS: Linux 2.6.32-45-pve x64
Warning: Task "bower-install-simple" failed. Use --force to continue.

Aborted due to warnings.

**Comment by Eluinhost** [comment]
I recently had to reinstall 3 instances of this on a new server and ran into the same thing, here is the notes I had from back then for how to install it:

```
Download auth project from https://github.com/Eluinhost/TeamspeakAuth
Follow the standard instructions apart from:
- Create a var folder
- Disable the bower-install task in grunt and `bower install` manually
- Need to modify font path in css to load from // instead of http:// because nginx is running https now
- Need to run php bin/console assets:install after the above change
- Need to run php bin/console assetic:dump --env=prod to install JS e.t.c
```

I'll take another look at it soon and see if I can fix the install task instead of working around it

**Comment by byRoadrunner** [comment]
I dont understand what you mean, can you help me to install it, maybe via Skype or Teamspeak3?

**Comment by Eluinhost** [comment]
If you want to pull the latest changes the last 3 commits and try again (after a `npm update`), I've just pushed do the following: 
- added a var folder so the console commands don't break
- upgraded the bower-install-simple task to a version that works
- fixed the https font path issue

Let me know if you have any other problems, I can't actually test it at the moment

**Comment by byRoadrunner** [comment]
Now it works, but if i open the webpage i always see this
![image](https://cloud.githubusercontent.com/assets/16355913/15190469/4a6cb93a-17b0-11e6-9201-f0587ada8acf.png)
and this error in apache:
[Wed May 11 13:43:17 2016] [error] File does not exist: /home/ts/TeamspeakAuth/web/images, referer: http://censored/app.php
[Wed May 11 13:43:19 2016] [error] File does not exist: /home/ts/TeamspeakAuth/web/js, referer: http://censored/app.php

**Comment by Eluinhost** [comment]
Can you try running:

```
php bin/console assets:install
php bin/console assetic:dump --env=prod
php bin/console cache:clear --env=prod
```

It looks like that is the raw template without any of the JS/CSS/fonts, those commands will install them for production and clear the cache so the new files are used.

**Comment by byRoadrunner** [comment]
ts@MCRBTest:~/TeamspeakAuth$ php bin/console cache:clear --env=prod
Clearing the cache for the prod environment with debug false [Symfony\Component\Filesystem\Exception\IOException]
Failed to remove file "/home/ts/TeamspeakAuth/cache/prod_old/fosJsRouting/data.json".



cache:clear [--no-warmup] [--no-optional-warmers]

**Comment by byRoadrunner** [comment]
http://37.228.134.87/app.php
There is always loading :(

**Comment by Eluinhost** [comment]
Yeah judging by the app.php in the URL and a 404 for 'partials/index' apache isn't routing properly. I personally use nginx so probably not very helpful in debugging it. Chances are the .htaccess in the web folder is either 1. not being read or 2. not working properly for your apache version. Is there anything in your apache logs that would help?

**Comment by Eluinhost** [comment]
Actually nevermind, I see it's nginx in the headers, what are you using for the routing?

**Comment by byRoadrunner** [comment]
I´ve changed the documentroot in the config

**Comment by byRoadrunner** [comment]
`[Wed May 11 15:24:01 2016] [error] [client 93.115.90.114] PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Failed to write cache file "/home/ts/TeamspeakAuth/app/../cache/prod/classes.php".' in /home/ts/TeamspeakAuth/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php:239\nStack trace:\n#0 /home/ts/TeamspeakAuth/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php(122): Symfony\\Component\\ClassLoader\\ClassCollectionLoader::writeCacheFile('/home/ts/Teamsp...', '<?php \\nnamespac...')\n#1 /home/ts/TeamspeakAuth/var/bootstrap.php.cache(2496): Symfony\\Component\\ClassLoader\\ClassCollectionLoader::load(Array, '/home/ts/Teamsp...', 'classes', false, false, '.php')\n#2 /home/ts/TeamspeakAuth/var/bootstrap.php.cache(2332): Symfony\\Component\\HttpKernel\\Kernel->doLoadClassCache('classes', '.php')\n#3 /home/ts/TeamspeakAuth/var/bootstrap.php.cache(2366): Symfony\\Component\\HttpKernel\\Kernel->boot()\n#4 /home/ts/TeamspeakAuth/web/app.php(13): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation in /home/ts/TeamspeakAuth/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php on line 239
[Wed May 11 15:24:27 2016] [notice] caught SIGTERM, shutting down
[Wed May 11 15:24:28 2016] [notice] Apache/2.2.22 (Debian) PHP/5.4.45-0+deb7u2 configured -- resuming normal operations
[Wed May 11 15:24:33 2016] [error] [client 93.115.90.113] File does not exist: /home/ts/TeamspeakAuth/web/partials, referer: http://37.228.134.87/app.php
[Wed May 11 15:32:35 2016] [error] [client 93.115.90.121] File does not exist: /home/ts/TeamspeakAuth/web/partials, referer: http://37.228.134.87/app.php
[Wed May 11 15:32:43 2016] [error] [client 93.115.90.121] File does not exist: /home/ts/TeamspeakAuth/web/partials, referer: http://37.228.134.87/app.php
`
